// <auto-generated />
using System;
using AhmadHRMSBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AhmadHRMSBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417234625_migration14")]
    partial class migration14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AhmadHRMSBackend.Models.AttendanceInfo.AttendanceInfo", b =>
                {
                    b.Property<int>("AttendanceInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceInfoId"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AttendanceInfoId");

                    b.ToTable("AttendanceInfo");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.AttendanceRecord.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.AttendanceSummary.AttendanceSummary", b =>
                {
                    b.Property<int>("AttendanceSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceSummaryId"));

                    b.Property<int>("Absent")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Late")
                        .HasColumnType("int");

                    b.Property<int>("Leave")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Present")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("AttendanceSummaryId");

                    b.HasIndex("EmployeeId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("AttendanceSummary");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Departments.Departments", b =>
                {
                    b.Property<int>("DepartmentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentsID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DepartmentsID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("PositionID");

                    b.HasIndex("StatusID");

                    b.ToTable("EmployeeList");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.LeaveRequests.LeaveRequests", b =>
                {
                    b.Property<int>("LeaveRequestsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestsID"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveRequestsID");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveStatusId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.LeaveStatus.LeaveStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("LeaveStatus");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.LeaveTypes.LeaveTypes", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Login.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsDeleted = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            IsDeleted = false,
                            RoleName = "HR"
                        },
                        new
                        {
                            RoleId = 3,
                            IsDeleted = false,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Login.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.PayrollRequests.PayrollRequests", b =>
                {
                    b.Property<int>("PayrollRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollRequestId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PayrollRequestId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId");

                    b.ToTable("PayrollRequests");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.PayrollStatus.PayrollStatus", b =>
                {
                    b.Property<int>("PayrollStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollStatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PayrollStatusId");

                    b.ToTable("PayrollStatus");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.Performance", b =>
                {
                    b.Property<int>("PerformanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceID"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextReview")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PerformanceID");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Performance");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.PerformanceAchievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("AchievementText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.HasKey("AchievementId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("PerformanceAchievement");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.PerformanceGoal", b =>
                {
                    b.Property<int>("PerformanceGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceGoalId"));

                    b.Property<string>("GoalText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.HasKey("PerformanceGoalId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("PerformanceGoal");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.PerformancePeriod", b =>
                {
                    b.Property<int>("PerformancePeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformancePeriodId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PerformancePeriodId");

                    b.ToTable("PerformancePeriod");

                    b.HasData(
                        new
                        {
                            PerformancePeriodId = 1,
                            IsDeleted = false,
                            PeriodName = "Q1 2026"
                        },
                        new
                        {
                            PerformancePeriodId = 2,
                            IsDeleted = false,
                            PeriodName = "Q2 2026"
                        },
                        new
                        {
                            PerformancePeriodId = 3,
                            IsDeleted = false,
                            PeriodName = "Q3 2026"
                        },
                        new
                        {
                            PerformancePeriodId = 4,
                            IsDeleted = false,
                            PeriodName = "Q4 2026"
                        },
                        new
                        {
                            PerformancePeriodId = 5,
                            IsDeleted = false,
                            PeriodName = "Q1 2027"
                        },
                        new
                        {
                            PerformancePeriodId = 6,
                            IsDeleted = false,
                            PeriodName = "Q2 2027"
                        },
                        new
                        {
                            PerformancePeriodId = 7,
                            IsDeleted = false,
                            PeriodName = "Q3 2027"
                        },
                        new
                        {
                            PerformancePeriodId = 8,
                            IsDeleted = false,
                            PeriodName = "Q4 2027"
                        },
                        new
                        {
                            PerformancePeriodId = 9,
                            IsDeleted = false,
                            PeriodName = "Q1 2028"
                        },
                        new
                        {
                            PerformancePeriodId = 10,
                            IsDeleted = false,
                            PeriodName = "Q2 2028"
                        },
                        new
                        {
                            PerformancePeriodId = 11,
                            IsDeleted = false,
                            PeriodName = "Q3 2028"
                        },
                        new
                        {
                            PerformancePeriodId = 12,
                            IsDeleted = false,
                            PeriodName = "Q4 2028"
                        },
                        new
                        {
                            PerformancePeriodId = 13,
                            IsDeleted = false,
                            PeriodName = "Q1 2029"
                        },
                        new
                        {
                            PerformancePeriodId = 14,
                            IsDeleted = false,
                            PeriodName = "Q2 2029"
                        },
                        new
                        {
                            PerformancePeriodId = 15,
                            IsDeleted = false,
                            PeriodName = "Q3 2029"
                        },
                        new
                        {
                            PerformancePeriodId = 16,
                            IsDeleted = false,
                            PeriodName = "Q4 2029"
                        },
                        new
                        {
                            PerformancePeriodId = 17,
                            IsDeleted = false,
                            PeriodName = "Q1 2030"
                        },
                        new
                        {
                            PerformancePeriodId = 18,
                            IsDeleted = false,
                            PeriodName = "Q2 2030"
                        },
                        new
                        {
                            PerformancePeriodId = 19,
                            IsDeleted = false,
                            PeriodName = "Q3 2030"
                        },
                        new
                        {
                            PerformancePeriodId = 20,
                            IsDeleted = false,
                            PeriodName = "Q4 2030"
                        });
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Position.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PositionID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.ReportPeriods", b =>
                {
                    b.Property<int>("ReportPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportPeriodId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportPeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportPeriodId");

                    b.ToTable("ReportPeriods");

                    b.HasData(
                        new
                        {
                            ReportPeriodId = 1,
                            IsDeleted = false,
                            ReportPeriodName = "Daily"
                        },
                        new
                        {
                            ReportPeriodId = 2,
                            IsDeleted = false,
                            ReportPeriodName = "Weekly"
                        },
                        new
                        {
                            ReportPeriodId = 3,
                            IsDeleted = false,
                            ReportPeriodName = "Monthly"
                        },
                        new
                        {
                            ReportPeriodId = 4,
                            IsDeleted = false,
                            ReportPeriodName = "Quarterly"
                        },
                        new
                        {
                            ReportPeriodId = 5,
                            IsDeleted = false,
                            ReportPeriodName = "Yearly"
                        });
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.ReportStatus", b =>
                {
                    b.Property<int>("ReportStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportStatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportStatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportStatusId");

                    b.ToTable("ReportStatus");

                    b.HasData(
                        new
                        {
                            ReportStatusId = 1,
                            IsDeleted = false,
                            ReportStatusName = "Completed"
                        },
                        new
                        {
                            ReportStatusId = 2,
                            IsDeleted = false,
                            ReportStatusName = "Scheduled"
                        },
                        new
                        {
                            ReportStatusId = 3,
                            IsDeleted = false,
                            ReportStatusName = "Draft"
                        });
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.ReportTypes", b =>
                {
                    b.Property<int>("ReportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportTypeId");

                    b.ToTable("ReportTypes");

                    b.HasData(
                        new
                        {
                            ReportTypeId = 1,
                            IsDeleted = false,
                            ReportTypeName = "Attendance"
                        },
                        new
                        {
                            ReportTypeId = 2,
                            IsDeleted = false,
                            ReportTypeName = "Payroll"
                        },
                        new
                        {
                            ReportTypeId = 3,
                            IsDeleted = false,
                            ReportTypeName = "Performance"
                        },
                        new
                        {
                            ReportTypeId = 4,
                            IsDeleted = false,
                            ReportTypeName = "Leave"
                        },
                        new
                        {
                            ReportTypeId = 5,
                            IsDeleted = false,
                            ReportTypeName = "Timesheet"
                        });
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.Reports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("ReportStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ReportPeriodId");

                    b.HasIndex("ReportStatusId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Status.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StatusID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.TimesheetDetails.TimesheetDetails", b =>
                {
                    b.Property<int>("TimesheetDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimesheetDetailId"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TimesheetId")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TimesheetDetailId");

                    b.HasIndex("TimesheetId");

                    b.ToTable("TimesheetDetails");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Timesheets.Timesheets", b =>
                {
                    b.Property<int>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimesheetId"));

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("OvertimeHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RegularHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TimesheetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.AttendanceRecord.AttendanceRecord", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.AttendanceSummary.AttendanceSummary", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithMany("AttendanceSummary")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.Departments.Departments", "Departments")
                        .WithMany("EmployeeList")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Position.Position", "Position")
                        .WithMany("EmployeeList")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Status.Status", "Status")
                        .WithMany("EmployeeList")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Position");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.LeaveRequests.LeaveRequests", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.LeaveStatus.LeaveStatus", "LeaveStatus")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.LeaveTypes.LeaveTypes", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveStatus");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Login.Users", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithOne("Users")
                        .HasForeignKey("AhmadHRMSBackend.Models.Login.Users", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Login.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.PayrollRequests.PayrollRequests", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithMany("PayrollRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.PayrollStatus.PayrollStatus", "PayrollStatus")
                        .WithMany("PayrollRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollStatus");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.Performance", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithMany("Performance")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Performance.PerformancePeriod", "PerformancePeriod")
                        .WithMany("Performances")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PerformancePeriod");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.PerformanceAchievement", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.Performance.Performance", "Performance")
                        .WithMany("PerformanceAcheivement")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.PerformanceGoal", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.Performance.Performance", "Performance")
                        .WithMany("PerformanceGoal")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.Reports", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.Departments.Departments", "Departments")
                        .WithMany("Reports")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Reports.ReportPeriods", "ReportPeriod")
                        .WithMany("Reports")
                        .HasForeignKey("ReportPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Reports.ReportStatus", "ReportStatus")
                        .WithMany("Reports")
                        .HasForeignKey("ReportStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AhmadHRMSBackend.Models.Reports.ReportTypes", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("ReportPeriod");

                    b.Navigation("ReportStatus");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.TimesheetDetails.TimesheetDetails", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.Timesheets.Timesheets", "Timesheet")
                        .WithMany("TimesheetDetails")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Timesheets.Timesheets", b =>
                {
                    b.HasOne("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Departments.Departments", b =>
                {
                    b.Navigation("EmployeeList");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.EmployeeList.EmployeeList", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("AttendanceSummary");

                    b.Navigation("LeaveRequests");

                    b.Navigation("PayrollRequests");

                    b.Navigation("Performance");

                    b.Navigation("Timesheets");

                    b.Navigation("Users")
                        .IsRequired();
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.LeaveStatus.LeaveStatus", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.LeaveTypes.LeaveTypes", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Login.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.PayrollStatus.PayrollStatus", b =>
                {
                    b.Navigation("PayrollRequests");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.Performance", b =>
                {
                    b.Navigation("PerformanceAcheivement");

                    b.Navigation("PerformanceGoal");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Performance.PerformancePeriod", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Position.Position", b =>
                {
                    b.Navigation("EmployeeList");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.ReportPeriods", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.ReportStatus", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Reports.ReportTypes", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Status.Status", b =>
                {
                    b.Navigation("EmployeeList");
                });

            modelBuilder.Entity("AhmadHRMSBackend.Models.Timesheets.Timesheets", b =>
                {
                    b.Navigation("TimesheetDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
